import type { Metadata } from 'next'
import { Major_Mono_Display, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"] 
})
const MMD = Major_Mono_Display({ 
  subsets: ['latin'] ,variable: '--font-Exo2',
  weight:["400"]
})

export const metadata: Metadata = {
  title: 'Rajyavardhan',
  description: 'Generated by RAGE',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <div className="flex w-full justify-center items-center align-middle">
          <nav id='showMe' className=" text-white p-4 fixed top-5 w-3/4 z-50 nav-glass rounded-full ">
            <div className="container mx-auto flex justify-between items-center">
              <div className={`text-xl font-bold logo-brand ${MMD.className}`}>rAjyAvArdhAn</div>

              <ul className="flex space-x-4">
                <li><a href="#" className="hover:text-gray-300">Home</a></li>
                <li><a href="#" className="hover:text-gray-300">About</a></li>
                <li><a href="#" className="hover:text-gray-300">Contact</a></li>
              </ul>
            </div>
          </nav>
        </div>
        {children}
        </body>
    </html>
  )
}
