import type { Metadata } from 'next'
import { Major_Mono_Display, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"] 
})
const MMD = Major_Mono_Display({ 
  subsets: ['latin'] ,variable: '--font-Exo2',
  weight:["400"]
})

export const metadata: Metadata = {
  title: 'Rajyavardhan',
  description: 'Generated by RAGE',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
